import Image from "next/image";
import Container from "./Container";
import { getProductCallouts, getProducts, getSiteSettings } from "@/lib/site-content";

export default async function ProductShowcase() {
  const [callouts, products, settings] = await Promise.all([getProductCallouts(), getProducts(), getSiteSettings()]);
  const product = products[0];
  const content = settings[0].productSection;
  if (!product) return null;
  return <section id="why" className="bg-cream py-24 sm:py-32"><Container><div className="grid gap-16 md:grid-cols-2 md:items-center">
    <div className="relative mx-auto w-full max-w-sm"><div className="absolute -inset-8 -z-10 rounded-[3rem] opacity-60 blur-2xl" style={{ background: "radial-gradient(closest-side, rgba(111,166,15,0.25), transparent 72%)" }} aria-hidden="true" /><div className="relative"><Image src={product.image.src} alt={product.image.alt} width={product.image.width} height={product.image.height} className="w-full rounded-[2rem] shadow-xl shadow-lime-deep/10" />{callouts.map((callout) => <span key={callout.id} className="absolute flex h-7 w-7 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-lemon font-display text-sm font-bold text-ink ring-4 ring-cream" style={{ top: callout.top, left: callout.left }}>{callout.n}</span>)}</div></div>
    <div className="max-w-lg"><p className="font-display text-sm font-semibold text-lime-deep">{content.eyebrow}</p><h2 className="mt-3 font-display text-4xl font-semibold leading-tight text-ink sm:text-[2.75rem]">{content.title}</h2><p className="mt-5 text-lg leading-relaxed text-ink/70">{content.body}</p><dl className="mt-10 space-y-7">{callouts.map((callout) => <div key={callout.id} className="flex gap-4"><dt className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-lime/15 font-display text-sm font-bold text-lime-deep">{callout.n}</dt><dd><p className="font-display font-semibold text-ink">{callout.title}</p><p className="mt-1 text-[15px] leading-relaxed text-ink/65">{callout.body}</p></dd></div>)}</dl></div>
  </div>{products.length > 1 && <div className="mt-16 border-t border-ink/10 pt-10"><p className="font-display text-lg font-semibold text-ink">More Aqua Spark sizes</p><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.slice(1).map((item) => <article key={item.id} className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-sm"><Image src={item.image.src} alt={item.image.alt} width={item.image.width} height={item.image.height} className="h-24 w-16 rounded-xl object-cover" /><div><h3 className="font-display text-lg font-semibold text-ink">{item.name} {item.size}</h3>{item.description && <p className="mt-1 text-sm leading-relaxed text-ink/65">{item.description}</p>}</div></article>)}</div></div>}</Container></section>;
}
